version: '3.9'

services:

  jekyll:
    build:
      context: .
    image: jekyll-starter
    command: jekyll foreman start
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    tty: true
    stdin_open: true
